//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookLoan
    {
        public int id { get; set; }
        public int mem_id { get; set; }
        public int doc_id { get; set; }
        public string Name { get; set; }
        public string BookName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string Description { get; set; }
        public string Condition { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
    
        public virtual DocumentRegistration DocumentRegistration { get; set; }
        public virtual MemberRegistration MemberRegistration { get; set; }
    }
}
