//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeletedMembers
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string NationalCode { get; set; }
        public Nullable<int> Credit { get; set; }
        public string Status { get; set; }
        public string OtherSpecifications { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<int> Classroom_id { get; set; }
        public string UserType { get; set; }
        public Nullable<int> BookLoan { get; set; }
        public string ClassName { get; set; }
    }
}
