//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeletedDocument
    {
        public int id { get; set; }
        public string BookName { get; set; }
        public string Writer { get; set; }
        public string Inventory { get; set; }
        public string Publisher { get; set; }
        public string CoverName { get; set; }
        public string PartNumber { get; set; }
        public string Price { get; set; }
        public string Date { get; set; }
        public string Topic { get; set; }
        public string Description { get; set; }
        public string HelpNumber { get; set; }
        public Nullable<int> BookLoan { get; set; }
    }
}
