//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Librarians
    {
        public int Log_id { get; set; }
        public string Log_UserName { get; set; }
        public string Log_Password { get; set; }
        public string NationalCode { get; set; }
    }
}
