//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryEntities : DbContext
    {
        public LibraryEntities()
            : base("name=LibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookLoan> BookLoan { get; set; }
        public virtual DbSet<Classroom> Classroom { get; set; }
        public virtual DbSet<DeletedBookLoan> DeletedBookLoan { get; set; }
        public virtual DbSet<DeletedDocument> DeletedDocument { get; set; }
        public virtual DbSet<DeletedMembers> DeletedMembers { get; set; }
        public virtual DbSet<DocumentRegistration> DocumentRegistration { get; set; }
        public virtual DbSet<Librarians> Librarians { get; set; }
        public virtual DbSet<log> log { get; set; }
        public virtual DbSet<MemberRegistration> MemberRegistration { get; set; }
        public virtual DbSet<BookReport> BookReport { get; set; }
        public virtual DbSet<UserReport> UserReport { get; set; }
    }
}
