//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReport
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string NationalCode { get; set; }
        public string UserType { get; set; }
        public int BookLoan { get; set; }
        public string ClassName { get; set; }
    }
}
